name: FastAPI CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (optional)
      run: echo "No tests yet, but you could add pytest here."

    - name: Build Docker image
      run: docker build -t Soumyad0670/fastapi-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${ secrets.DOCKER_USERNAME }
        password: ${ secrets.DOCKER_PASSWORD }

    - name: Push Docker image
      run: docker push Soumyad0670/fastapi-app

# Deployed using docker-compose on a server